server:
  port: 14000
spring:
  application:
    name: gulimall-member
  #    mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://1.117.152.124/gulimall_ums
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.152.124:8848
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl