server:
  port: 13000


spring:
  application:
    name: gulimall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.152.124:8848 #nacos注册中心地址
  thymeleaf:
    cache: false
  redis:
    host: 1.117.152.124
    port: 6379