server:
  port: 3333
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.152.124:8848
    #    oss配置
    alicloud:
      access-key: LTAI4G9qTMpZUXiTFFb6NpTc
      secret-key: K8VVKnc6B2
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-i
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        template: TP1711063
        appcode: 0a0bfd5938d14452b42379b0988580bb